openapi: 3.0.0
info:
  title: REAL SERVICES Ltd API
  description: The CMS api that helps to coordinate the daily transactions at the company.
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://producation.app/api
    description: production server

paths:
  /users:
    get:
      summary: Returns a list of users.
      responses:
        '200': 
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string